### ISSUE TITLE
Need to update the Jakarta EE 8 TCK release

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/cdi-tck#208]
While there was a 2.0.6.SP1 release to maven, we did not update the Jakarta EE 8 TCK, so that needs to happen as well.

**Comment by manovotn** [comment]
Well, the release did the artifact upload part as well; check the job config. Is there some new place where it should be uploaded?

We should probably create a Wiki page on the repo describing these things...

**Comment by starksm64** [comment]
Yes, I'm just going to add the upload step to the script you created. Yes, definitely need to wiki describing the various jenkins jobs.
