### ISSUE TITLE
Tests that reference optional technologies moved from Java SE 8 to Jakarta EE 9 should be removed or made optional

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/cdi-tck#215]
As [per the Jakarta EE 9 release plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan) any CDI tests that reference the below mentioned **optional** technologies should be removed or made optional.:

```
Specifications Added to Jakarta EE 9

The following specifications previously part of Java SE 8 will be added to Jakarta EE 9 either as required or optional specifications as indicated and MUST be moved to the jakarta namespace.

    Jakarta Activation (Required)
    Jakarta XML Binding (Optional)
    Jakarta XML Web Services (Optional)
    Jakarta Web Services Metadata (Optional)
    Jakarta SOAP with Attachments (Optional)
```

Note that this impacts both Full Platform + Web Profile.

**Comment by starksm64** [comment]
I don't think there is any question that the associated tests need to move to the javaee-full test group that CDI has. The question is, how are optional tests handled. Would we need a new javaee-full-optional group as well?

@scottmarlow what does the full tck run do now when it is validating optional tests?

**Comment by scottmarlow** [comment]
> what does the full tck run do now when it is validating optional tests?

The Platform TCK (Full) run allows optional tests to be included or excluded via keywords defined in [keyword.properties](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/lib/harness/keyword.properties#L233) which is [described in the TCK user guide doc](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/user_guides/jakartaee/src/main/jbake/content/using.adoc).  

To skip the webservices tests we could use `ant -Dkeywords="!webservices" runclient` to skip the tests marked as Web Services tests but still run other tests.  Typically, the actual used `keywords` expression is more complex (e.g. also specifies certain other Full Platform/Web Profile specific keywords).

> I don't think there is any question that the associated tests need to move to the javaee-full test group that CDI has.

Doesn't the above quoted text from https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan need to be addressed by ensuring that the (optional) Web Services do not have to be run with the (CDI) javaee-full test group?  

My thought on this is that some Jakarta EE Full Platform implementations will not implement the optional technologies mentioned above and would see CDI TCK failures when using the javaee-full test group, if the relevant tests aren't removed.

**Comment by starksm64** [comment]
The plan only indicates what specs are optional. The profile spec indicates
which specifications make up the profile, and the web profile does not
reference JWS, so those tests should not be in that set of tests. I thought
that is what we decided on this week's committee call, but we will bring it
up on both the platform and spec calls.

**Comment by scottmarlow** [comment]
> The plan only indicates what specs are optional. The profile spec indicates
> which specifications make up the profile, and the web profile does not
> reference JWS, so those tests should not be in that set of tests. 

Does the CDI TCK still need changes to allow for full platform implementations that do not implement optional JWS?

**Comment by starksm64** [comment]
Yes because it currently has no notion of a test group that could be used
to isolate the JWS tests. I think we need a javaee-full-optional group
added.

**Comment by edbratt** [comment]
@lanceanderson any thoughts on how this would best be accomplished?

**Comment by starksm64** [comment]
Looking into this further, we had already removed the JWS tests from the TCK. There are no tests that refer to the wsdl or remaining class that uses the jakarta.jws.* types. I'll create a separate staging release for testing that has these vestiges removed.

**Comment by starksm64** [comment]
Try this version:
https://download.eclipse.org/ee4j/cdi/3.0/cdi-tck-3.0.2-dist.zip

**Comment by scottmarlow** [comment]
https://ci.eclipse.org/jakartaee-tck/job/cditck-porting/job/master/85 is testing https://download.eclipse.org/ee4j/cdi/3.0/cdi-tck-3.0.2-dist.zip with Web Profile.  I expect the same failure to occur due to what looks like an annotation scanning bug mentioned in https://github.com/eclipse-ee4j/glassfish/issues/23184.  I now believe that based on your assessment of the CDI TCK that not further failures are expected after https://github.com/eclipse-ee4j/glassfish/issues/23184 is fixed.

https://ci.eclipse.org/jakartaee-tck/job/cditck-porting/job/master/86 is testing https://download.eclipse.org/ee4j/cdi/3.0/cdi-tck-3.0.2-dist.zip with Full Platform, I expect this test to pass.

**Comment by scottmarlow** [comment]
Since there are no jakarta.xml.ws.WebServiceRef's actually used by CDI TCK tests, I don't think that we need to do anything else for this issue.

**Comment by scottmarlow** [comment]
Please reopen if this issue is needed.
