### ISSUE TITLE
persistence.xml is not using Jakarta EE 9 schemas

### ISSUE THREAD

**Issue by smillidge** [eclipse-ee4j/cdi-tck#216]
The following file does not reference the Jakarta EE 9 schema https://github.com/eclipse-ee4j/cdi-tck/blob/master/impl/src/main/resources/org/jboss/cdi/tck/tests/implementation/simple/resource/persistenceContext/persistence.xml

**Comment by starksm64** [comment]
The persistence.xml files were updated in 248dbcd0a4c32cdfc55e04b3fd4ddab13c3ac3c7

**Comment by gurunrao** [comment]
@starksm64 @smillidge 
Jakarta EE 9 schemas are applicable to CDI TCK 3.0+, we should merge the TCK fix to 3.0 CDI TCK branch. when used with Jakarta EE 9 environment, we have encountered similar exception with CDI TCK 3.0.
