### ISSUE TITLE
Contribute the User Guide

### ISSUE THREAD

**Issue by edbratt** [eclipse-ee4j/cdi-tck#225]
This project refers to the [Java EE JCP based TCK User Guide](http://docs.jboss.org/cdi/tck/reference/latest/en-US/html/). Please consider contributing this to the Jakarta EE project so that it can be updated with the correct process details can be included (as well as updates related to Jakarta versions, etc.)

**Comment by starksm64** [comment]
the user guide is located in the cdi-tck/doc/reference/src/main/asciidoc/ of this repository. That link is out of date and needs to be updated on the root readme.

**Comment by starksm64** [comment]
The main README now links to the GitHub pages version of the generated TCK user guide.
