### ISSUE TITLE
Use CDI_FULL test group to exclude @Interceptors tests

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/cdi-tck#262]
Breaking up the sets of tests into separate categories, first @Interceptors based tests need to added to the CDI_FULL test group.

**Comment by starksm64** [comment]
I think we are good to close this.

**Comment by graemerocher** [comment]
@manovotn @starksm64 @Ladicek what was the final decision on `@AroundInvoke` in the target class. I see definitions like:

https://github.com/eclipse-ee4j/cdi-tck/blob/master/impl/src/main/java/org/jboss/cdi/tck/interceptors/tests/contract/aroundInvoke/Bean3.java

Are included with the `lite` tests?

**Comment by manovotn** [comment]
@graemerocher you are right, this isn't supposed to be in Lite.
 `cdi-tck/impl/src/main/java/org/jboss/cdi/tck/interceptors/tests/` is where all interceptor specification TCK tests are. I think I reworked most interceptors tests to operate on interceptors with bindings and we didn't want to split interceptors TCK into different packages.

I must have missed this one (and possibly others?), it was lots and lots of tests...
Looking at the assertions, it seems to be testing this:
```
        <group>
            <text>Around-invoke methods can have |public|, |private|, |protected|, or |package| level access.</text>
            <assertion id="ca">
                <text>Test |public| level access.</text>
            </assertion>
            <assertion id="cb">
                <text>Test |private| level access.</text>
            </assertion>
            <assertion id="cc">
                <text>Test |protected| level access.</text>
            </assertion>
            <assertion id="cd">
                <text>Test |package| level access.</text>
            </assert
```

Which means this TCK test can be rewritten to use the standard interceptor with bindings.
But we should then keep a copy of this test (or verify there is other similar) for CDI Full.

**Comment by graemerocher** [comment]
@manovotn thanks for the clarification. There seem to be several cases, like this one as well:

https://github.com/eclipse-ee4j/cdi-tck/blob/master/impl/src/main/java/org/jboss/cdi/tck/interceptors/tests/order/aroundInvoke/Vehicle.java

**Comment by manovotn** [comment]
Yeah, most of the reworks I did were focused around `@Interceptors` and other stuff that was `grep`-able.

The one you mentioned will need to be marked Full and we'll need to make a similar version for Lite with only the supported bits (so that we don't coverage on this).

**Comment by manovotn** [comment]
Feel free to send PRs or, at the very least, please create new issue(s) for them so we keep track of all of them.
