### ISSUE TITLE
Use CDI_FULL to exclude portable extension tests

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/cdi-tck#265]
Breaking up the sets of tests into separate categories, portable extension based tests need to added to the CDI_FULL test group.

**Comment by manovotn** [comment]
Two parts are sent, reviewed and merged and I am hoping to post the remaining part today or tomorrow. 
Most of it should hopefully be just moving tests to `full` package as they already reside in packages suggesting tests purely for portable extensions (therefore with no test coverage loss for Lite)

**Comment by manovotn** [comment]
I've sent the last part of changes. If accepted, this issue can IMO be resolved.
