### ISSUE TITLE
CDI-lite test update strategy

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/cdi-tck#273]
Based on today's CDI call, we want to revert #256, and then redo it in smaller stages based on small blocks of packages of tests after first applying the cdi-full group to tests based on:
* #262 
* #263 
* #264 
* #265 
* #289

We also want to move the cdi-full tests into a new package to separate them from the lite tests as this regrouping is done. The issue for that is #272.

**Comment by manovotn** [comment]
Note that we didn't make an issue for specialization tests. I tried addressing that as I went over https://github.com/eclipse-ee4j/cdi-tck/issues/289 but a few tests might have slipped through. It should be easy enough to catch once MN starts executing their Lite impl though (which presumably lacks specialization support).

Then there is the question of injection of `BeanManager` into tons of tests and also into the test super class (`AbstractTest`).
We would either have to change it everywhere or we could simply allow `BeanManager` injection even in Lite but restrict the set of usable methods (which is what I would vote for) - users are used to `BeanManager` anyway, so it might be a common attempt to inject it even in Lite.

**Comment by starksm64** [comment]
Thanks @manovotn, when I pulled in the changes into a clone of cdi-tck upstream and ran against the weld core tck-runner, I'm seeing one error:
```
[ERROR] Tests run: 1205, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 46.857 s <<< FAILURE! - in TestSuite
[ERROR] org.jboss.cdi.tck.tests.full.inheritance.specialization.simple.broken.noextend1.SpecializingBeanImplementsInterfaceOnly.arquillianBeforeClass  Time elapsed: 0.051 s  <<< FAILURE!
java.lang.RuntimeException: Expected exception of type jakarta.enterprise.inject.spi.DefinitionException during deployment of _DEFAULT_, but no exception was thrown.
```

Add a dependent qualifier to Donkey_Broken fixed the issue.

**Comment by manovotn** [comment]
Interesting, I even double checked that and always had all tests passing. Don't know how come it didn't fail for me. The change you made seems correct

**Comment by manovotn** [comment]
@starksm64 hmm, this test is not executed for me (which is why I missed it) when I do `mvn clean verify` and I cannot seem to figure out why.
When I ran it explicitly (`-Dtest=..`) then it indeed fails because it missed the `@Dependent` annotation *and* it should be `CDI_FULL` group.

Did you execute those tests in any other way? Or do you have any other extra commit changing some setup?
I can see other tests in `full` package executed perfectly well, just this one is somehow left out...

**Comment by starksm64** [comment]
Ok, strange. I was  using the embedded profile jboss-tck-runner with the tck-core-suite.xml, so I had added that to the surefire configuration:

+                            <suiteXmlFiles>
+                                <suiteXmlFile>target/suites/tck-core-suite.xml</suiteXmlFile>
+                            </suiteXmlFiles>

That is the difference. TestNG will scan all classes for annotations while without this surefire is just scanning the dependencies for *Test classes.

**Comment by manovotn** [comment]
Hmm, so the default profile in Weld doesn't have this applied automatically? I need to remember to look at that on Mon...
But you are right that this indeed looks like the cause, thanks for the hint!
