### ISSUE TITLE
Address missing bean defining annotations in Lite portion of tests

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/cdi-tck#289]
With the non-Lite tests moved under the full package and labelled with the cdi-full test group, the Weld jboss-tck-runner emedded tests show the following failure count due to missing bean defining annotations:

[ERROR] Tests run: 1423, Failures: 385, Errors: 0, Skipped: 245

The next step in #273 is to add the missing bean defining annotations to obtain a clean run of the core tests under Weld.

**Comment by manovotn** [comment]
@starksm64 I was planning on doing this once your PR was merged. If you want, I can take it over.

**Comment by starksm64** [comment]
@manovotn sure, go ahead. I am currently working on #290 as I saw several decorator related tests using the Decorated qualifier that were not moved to cdi-full. I'm half way through that, so a PR will be coming shortly so you can avoid updating those tests.

**Comment by manovotn** [comment]
Alright, I will start working on this tomorrow :)

**Comment by starksm64** [comment]
@manovotn with the latest changes it looks like we are down to 95 errors with Weld on core tests:
```
[ERROR] Tests run: 1274, Failures: 95, Errors: 0, Skipped: 79
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:09 min
[INFO] Finished at: 2021-09-23T06:42:51-05:00
[INFO] ------------------------------------------------------------------------
```

You mentioned being off at some point this week, so just assign this issue to me if you don't finish before you leave.

**Comment by manovotn** [comment]
@starksm64 yea, I have covered most at this point and I plan on finishing that today or tomorrow :-)
BTW I will be off next Tue through Fri.
