### ISSUE TITLE
More decorator related tests need the cdi-full test group

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/cdi-tck#290]
In looking at current core tests failures related to missing bean defining annotations, I came across the org.jboss.cdi.tck.tests.implementation.builtin.metadata.broken.injection.decorated package tests. These are using @Decorated and validating the requirements around that qualifier. 

Another test is org.jboss.cdi.tck.tests.implementation.builtin.metadata.broken.injection.BuiltinDecoratorInjectionTest

**Comment by starksm64** [comment]
@manovotn can you look at the org.jboss.cdi.tck.tests.lookup.injectionpoint.{InjectableReferenceTest,InjectionPointTest} test. There are several decorators in there, but they don't seem to be tested. Not sure if those tests should move to cdi-full, so I left them alone.

**Comment by manovotn** [comment]
Both decorators are in fact used. However, the one in `InjectableReferenceTest` can be replaced by interceptor (as it tests something unrelated to decorators).
The other test needs to be partly moved to Full.
I have sent a PR that addresses these two tests - https://github.com/eclipse-ee4j/cdi-tck/pull/292
