### ISSUE TITLE
Create negative tests for build compatible extensions

### ISSUE THREAD

**Issue by manovotn** [eclipse-ee4j/cdi-tck#321]
Build compatible extensions (in their `@Enhancement` and `@Registration`) phases state that their methods need to have exactly one parameter from certain types.

We should provide tests that break these restrictions (multiple or no params) and are expecting a deployment problem.

**Comment by Ladicek** [comment]
It's not `@Synthesis`, it's `@Registration`.

**Comment by manovotn** [comment]
> It's not `@Synthesis`, it's `@Registration`.

OFC, I am bad at talking and typing simultaneously :)
I've edited the issue description.
