### ISSUE TITLE
Verify that Lite tests are not using a beans.xml content other than bean-discovery-mode attribute to affect behavior

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/cdi-tck#334]
It was brought up on today's spec call that there are Lite tests that are dictating behavior by beans.xml content other than the bean-discovery-mode attribute. These need to be investigated.

**Comment by manovotn** [comment]
> It was brought up on today's spec call that there are Lite tests...

Any chance we can ask whoever identified the issue to give us name of those tests? Going through all tests out there would be very time demanding :-)
I suppose those are some tests that manually add `beans.xml`? Since those added via `WebArchiveBuilder().withBeansXml()` should add anything changing the behavior.

**Comment by starksm64** [comment]
The first one pointed out was org.jboss.cdi.tck.tests.alternative.broken.incorrect.name.stereotype.NoAnnotationWithSpecifiedNameTest that is expecting a failure due to a test specific beans.xml. It is those tests calling withBeansXml(...) to add test specific mods without a full group tag that are the problem. There do seem to be a few.

**Comment by manovotn** [comment]
@starksm64 that test doesn't have wrong beans.xml, it should simply be a CDI Full test.
Its purpose is to verify what happens if you declare a non-existing stereotype annotation inside beans.xml.

**Comment by starksm64** [comment]
Right, that is the problem; It is not in the full test group, so Micronaut was seeing this as a failure while running the Lite tests. Adding the correct group to these tests is the point of this issue.

**Comment by manovotn** [comment]
Aah ok, I thought the issue is that there are actual tests aimed to test Lite behavior but have CDI Full-like beans.xml.
Got it.
