### ISSUE TITLE
Create a separate cdi-lite-api-jdk11.sig file?

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/cdi-tck#347]
Do we need a separate cdi-lite-api-jdk11.sig file that excludes the jakarta.interceptor classes that are not appropriate for a CDI Lite implementation? If such an implementation would depend on the jakarta version, it would just have these extra classes, but if an implementation provides its own, it may not create classes are are not needed (AroundInvoke, Interceptors, ...).

**Comment by Ladicek** [comment]
The classes that are not relevant to CDI Lite are, to the best of my knowledge:

- `AroundTimeout`
- `Interceptors`

And most likely also:

- `ExcludeClassInterceptors`
- `ExcludeDefaultInterceptors`

Out of these 4, 3 of them are irrelevant to CDI Full as well. So IMHO, if noone created a stripped down version of the Interceptor API for CDI before 4.0, I don't see anyone creating a stripped down version of the Interceptor API for CDI Lite.

**Comment by Emily-Jiang** [comment]
agreed with @Ladicek! `Interceptors` are used by EJBs.

**Comment by starksm64** [comment]
So on the call today it was decided that Lite implementations should not have a separate signature test. The reasoning was that:

1. It is simply to meet the requirement be depending on the Jakarta Interceptors API artifact
2. We have said we don't want to limit what Lite implementations can do, meaning they are free to support features from Full and Interceptors.
