### ISSUE TITLE
InvalidatingSessionDestroysConversationTest doesn't configure Faces correctly

### ISSUE THREAD

**Issue by Azquelt** [eclipse-ee4j/cdi-tck#367]
It looks like [`InvalidatingSessionDestroysConversationTest`](https://github.com/eclipse-ee4j/cdi-tck/blob/master/web/src/main/java/org/jboss/cdi/tck/tests/context/conversation/InvalidatingSessionDestroysConversationTest.java) is meant to work like this:

* Make a request which is handled by Faces using `clouds.xhtml`, which looks up the ConversationScoped `Cloud` bean and starts a long-running conversation
* Assert that no `Cloud` bean has been destroyed yet (i.e. the conversation has not been destroyed yet)
* Invalidate the session
* Assert that a `Cloud` bean has been destroyed (because invalidating the session destroyed the conversation)

However, I don't think the test is set up correctly for Faces to handle the call to `clouds.xhtml`
* [The test makes a request to `clouds.xhtml`](https://github.com/eclipse-ee4j/cdi-tck/blob/master/web/src/main/java/org/jboss/cdi/tck/tests/context/conversation/InvalidatingSessionDestroysConversationTest.java#L63)
* However, the [web.xml only seems to configure the Faces servlet to handle requests matching `*.jsf`](https://github.com/eclipse-ee4j/cdi-tck/blob/master/web/src/main/resources/org/jboss/cdi/tck/tests/context/conversation/web.xml#L28-L31)
* This would mean that clouds.xhtml is just served as a plain file and the `Cloud` bean instance is never created and so isn't destroyed

It looks like the [3.0 version of this test](https://github.com/eclipse-ee4j/cdi-tck/blob/3.0/impl/src/main/java/org/jboss/cdi/tck/tests/context/conversation/InvalidatingSessionDestroysConversationTest.java#L60) made the request to `clouds.jsf` rather than `clouds.xhtml`. This was changed in #315 and I think it should be changed back.

**Comment by Azquelt** [comment]
It looks like #315 also changed the web.xml but that change was reverted in #318, where @manovotn notes that he was seeing this test fail on WildFly.

**Comment by Azquelt** [comment]
I should also note that I don't have much experience with Faces so I may have misunderstood something about this test, but the test changes since 3.0 look wrong to me and do explain the failure I'm seeing.

**Comment by manovotn** [comment]
I am faces noob myself so I might have mangled the test. Plus at the time of writing there was just about zero EE servers to run reliably against :)
